---

- name: Fail When Using Wrong mongodb_version Variable with RHEL / CentOS / Oracle
  fail:
    msg: "mongodb_version variable should be '3.4' or '3.6' or '4.0' or '4.2' or '4.4' or '5.0' or '6.0' for RedHat family"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("3.4|3.6|4.0|4.2|4.4|5.0|6.0|7.0")
    - ansible_os_family == 'RedHat'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install EPEL Release Repository
  package:
    name: epel-release
    state: present
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Add GPG Key for MongoDB Repository
  rpm_key:
    key: "{{ mongodb_repository_rpm_key }}"
    state: present
  register: _yum
  until: _yum is succeeded
  retries: 5
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Add MongoDB YUM Repository
  yum_repository:
    name: "mongodb-{{ mongodb_version }}"
    description: "Official MongoDB {{ mongodb_major_version }} yum repo"
    baseurl: "{{ mongodb_repository[mongodb_major_version] }}"
    gpgcheck: true
    gpgkey: "{{ mongodb_repository_gpg_key }}"
  register: _yum
  until: _yum is succeeded
  retries: 5
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install MongoDB Package '{{ mongodb_version }}'
  yum:
    name:
      - "{{ mongodb_package + '-server=' + mongodb_version if mongodb_version | length > 3 else mongodb_package + '-server' }}"
      - "{{ mongodb_package + '-tools=' + mongodb_version if mongodb_version | length > 3 else mongodb_package + '-tools' }}"
    state: "{{ mongodb_package_state }}"
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_main_group != mongos_host_group
  tags: [mongodb, mongodb-install]

- name: Install Mongos Package '{{ mongos_version }}'
  yum:
    name: "{{ mongos_package + '=' + mongos_version if mongos_version | length > 3 else mongos_package }}"
    state: "{{ mongos_package_state }}"
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_main_group == mongos_host_group
  tags: [mongos, mongos-install]

- name: Install Mongo shell When MongoDB Version < '4.4'
  yum:
    name: "{{ mongodb_package + '-shell=' + mongodb_version if mongodb_version | leng    th > 3 else mongodb_package + '-shell' }}"
    state: present
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_major_version is version('4.4', '<')
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install Mongosh When MongoDB Version >= '4.4'
  yum:
    name: mongodb-mongosh
    state: present
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_major_version is version('4.4', '>=')
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install Numactl Package
  yum:
    name: numactl
    state: present
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_use_numa
  tags: [mongodb, mongos, mongodb-install, mongos-install]
